

#debug
=Just print echo 
make -s 

=Print shell command
make -n

=Print all variables. Wired-name variable is useful to debug
make -p

=Pirnt a message
$(warning ...)

=Etc
--warn-undefined-variables
